# Generated by Django 3.0.5 on 2020-11-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='product_images/')),
                ('details_description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
