# Generated by Django 3.0.5 on 2020-11-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app23', '0003_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
