# Generated by Django 3.0.5 on 2020-11-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app23', '0004_auto_20201113_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('products_quantity', models.IntegerField()),
                ('actual_price', models.IntegerField()),
                ('discounted', models.IntegerField()),
                ('total_bill', models.IntegerField()),
            ],
        ),
    ]
